name: 'Annotations Action'
description: 'Creates annotations from a JSON file'
inputs:
  repo-token:
    description: 'Token used to interact with the GitHub API.'
    required: true
  input:
    description: 'Path to a JSON file which contains a list of annotations.'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
